# Generated by Django 4.0.6 on 2022-07-06 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0002_auto_20190603_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crudsimple',
            old_name='Alamat',
            new_name='fakultas',
        ),
        migrations.RenameField(
            model_name='crudsimple',
            old_name='Divisi Pekerjaan',
            new_name='jurusan',
        ),
        migrations.RenameField(
            model_name='crudsimple',
            old_name='Nama',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='crudsimple',
            name='NIP',
        ),
    ]
