# Generated by Django 4.0.6 on 2022-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0003_rename_alamat_crudsimple_fakultas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudsimple',
            name='gender',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], default='Pria', max_length=50),
        ),
    ]
