# Generated by Django 4.0.6 on 2022-07-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0004_alter_crudsimple_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudsimple',
            name='gender',
            field=models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], default='Pria', max_length=50),
        ),
    ]
