# Generated by Django 4.0.6 on 2022-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0005_alter_crudsimple_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crudsimple',
            name='gender',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], default='Pria', max_length=50),
        ),
        migrations.AlterField(
            model_name='crudsimple',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crudsimple',
            name='nip',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
