# Generated by Django 4.0.6 on 2022-07-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0006_alter_crudsimple_gender_alter_crudsimple_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudsimple',
            name='id',
        ),
    ]
