# Generated by Django 4.0.6 on 2022-07-17 16:38

from django.db import migrations, models
import simplecrud.models


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0008_alter_crudsimple_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudsimple',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=simplecrud.models.get_file_path_foto),
        ),
    ]
