# Generated by Django 4.0.6 on 2022-07-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplecrud', '0009_crudsimple_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crudsimple',
            old_name='image',
            new_name='foto',
        ),
    ]
